version: "3"

services:
  stay-spotter-api:
    build: ./api
    ports:
      - "8800:8800"
    networks:
      - stay-spotter-network
    env_file:
      - .env
    restart: always

  stay-spotter-client:
    build: ./client
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    depends_on:
      - stay-spotter-api
    networks:
      - stay-spotter-network
    env_file:
      - .env

networks:
  stay-spotter-network:
    driver: bridge
